#ifndef MESSAGETYPES_H
#define MESSAGETYPES_H

#define LOGIN_REQ "loginReq"
#define LOGIN_RSP "loginRsp"
#define LOGOUT_REQ "logoutReq"
#define LOGOUT_RSP "logoutRsp"
#define NEW_TASK_REQ "newTaskReq"
#define NEW_TASK_RSP "newTaskRsp"
#define EDIT_TASK_REQ "editTaskReq"
#define EDIT_TASK_RSP "editTaskRsp"
#define DELETE_TASK_REQ "deleteTaskReq"
#define DELETE_TASK_RSP "deleteTaskRsp"
#define ASSIGN_TASK_TO_TA_LIST_REQ "assignTaskToTaListReq"
#define ASSIGN_TASK_TO_TA_LIST_RSP "assignTaskToTaListRsp"
#define EVALUATE_TASK_FOR_TA_REQ "evaluateTaskForTaReq"
#define EVALUATE_TASK_FOR_TA_RSP "evaluateTaskForTaRsp"
#define TASK_LIST_FOR_TA_REQ "taskListForTaReq"
#define TASK_LIST_FOR_TA_RSP "taskListForTaRsp"
#define TASK_LIST_FOR_INSTRUCTOR_REQ "taskListForInstructorReq"
#define TASK_LIST_FOR_INSTRUCTOR_RSP "taskListForInstructorRsp"
#define NEW_COURSE_REQ "newCourseReq"
#define NEW_COURSE_RSP "newCourseRsp"
#define EDIT_COURSE_REQ "editCourseReq"
#define EDIT_COURSE_RSP "editCourseRsp"
#define DELETE_COURSE_REQ "deleteCourseReq"
#define DELETE_COURSE_RSP "deleteCourseRsp"
#define COURSE_LIST_FOR_TA_REQ "courseListForTaReq"
#define COURSE_LIST_FOR_TA_RSP "courseListForTaRsp"
#define COURSE_LIST_FOR_INSTRUCTOR_REQ "courseListForInstructorReq"
#define COURSE_LIST_FOR_INSTRUCTOR_RSP "courseListForInstructorRsp"
#define NEW_TA_REQ "newTaReq"
#define NEW_TA_RSP "newTaRsp"
#define TA_LIST_FOR_INSTRUCTOR_REQ "taListForInstructorReq"
#define TA_LIST_FOR_INSTRUCTOR_RSP "taListForInstructorRsp"
#define NEW_INSTRUCTOR_REQ "newInstructorReq"
#define NEW_INSTRUCTOR_RSP "newInstructorRsp"
#define INSTRUCTOR_LIST_REQ "instructorListReq"
#define INSTRUCTOR_LIST_RSP "instructorListRsp"

#endif // MESSAGETYPES_H
